name: deploy hexo

on:
  push:
    branches:
      - master

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Use Node.js v12.x
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: |
          git clone https://github.com/f-dong/hexo-theme-minimalism.git themes/hexo-theme-minimalism
          mv -f theme_config.yml themes/hexo-theme-minimalism/_config.yml
          npm install
          npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          full_commit_message: ${{ github.event.head_commit.message }}
          keep_files: true